name: sccmec
description: A tool for typing SCCmec cassettes in assemblies
icon: false
keywords:
  - fasta
  - resistance
  - Staphylococcus aureus
modules:
  - sccmec
input:
  - meta:
    type: map
    description: |
      Groovy Map containing sample information
      e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: The final assembly in FASTA format
      pattern: "*.{fna,fna.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tsv:
      type: file
      description: A tab-delimited file with the predicted PBP type
      pattern: "*.tsv"
  - merged_tsv:
      type: file
      description: A merged TSV of all sccmec result files
      pattern: "sccmec.tsv"
  - blast:
      type: file
      description: A tab-delimited file of all blast hits
      pattern: "*.tblastn.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
docs:
  meta:
    title: sccmec
    description: >-
      A Bactopia Tool which uses sccmec for typing SCCmec cassettes
      in _Staphylococcus aureus_ assemblies.
  introduction: |
      The `sccmec` module uses [sccmec](https://github.com/rpetit3/sccmec) for typing
      SCCmec cassettes in _Staphylococcus aureus_ assemblies.
  output:
    tree: |
      <BACTOPIA_DIR>
      ├── <SAMPLE_NAME>
      │   └── tools
      │       └── sccmec
      │           ├── <SAMPLE_NAME>.blastn.tsv
      │           ├── <SAMPLE_NAME>.details.tsv
      │           ├── <SAMPLE_NAME>.tsv
      │           └── logs
      │               ├── nf-sccmec.{begin,err,log,out,run,sh,trace}
      │               └── versions.yml
      └── bactopia-runs
          └── sccmec-<TIMESTAMP>
              ├── merged-results
              │   ├── logs
              │   │   └── sccmec-concat
              │   │       ├── nf-merged-results.{begin,err,log,out,run,sh,trace}
              │   │       └── versions.yml
              │   └── sccmec.tsv
              └── nf-reports
                  ├── sccmec-dag.dot
                  ├── sccmec-report.html
                  ├── sccmec-timeline.html
                  └── sccmec-trace.txt
    add_note: true
    folders:
      - name: Merged Results
        description: |
          Below are results that are concatenated into a single file.
        table:
          - id: sccmec.tsv
            description: A merged TSV file with `sccmec` results from all samples
      - name: sccmec
        description: |
          Below is a description of the _per-sample_ results from [sccmec](https://github.com/rpetit3/sccmec).
        is_extensions: true
        table:
          - id: .blastn.tsv
            description: A tab-delimited file of all blast hits
          - id: .details.tsv
            description: A tab-delimited file with details for each serogroup
          - id: .tsv
            description: A tab-delimited file with the predicted PBP type
  citations:
    - csvtk
    - sccmec
