name: "sccmec"
description: A tool for typing SCCmec cassettes in assemblies
keywords:
  - bacteria
  - sccmec
  - fasta
  - assembly
tools:
  - "sccmec":
      description: "In silico SCCmec typing for Staphylococcus aureus assemblies"
      homepage: "https://github.com/rpetit3/sccmec"
      documentation: "https://github.com/rpetit3/sccmec"
      tool_dev_url: "https://github.com/rpetit3/sccmec"
      doi: ""
      licence: "['MIT']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: An assembly in FASTA format
      pattern: "*.{fasta,fasta.gz,fna,fna.gz,fa,fa.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - tsv:
      type: file
      description: A tab-delimited file with the predicted PBP type
      pattern: "*.tsv"
  - targets:
      type: file
      description: A tab-delimited file of all target-specific blast hits
      pattern: "*.targets.blastn.tsv"
  - targets_details:
      type: file
      description: A tab-delimited file with details for each type based on targets
      pattern: "*.targets.details.tsv"
  - regions:
      type: file
      description: A tab-delimited file of all full cassette blast hits
      pattern: "*.regions.blastn.tsv"
  - regions_details:
      type: file
      description: A tab-delimited file with details for each type based on full cassettes
      pattern: "*.regions.details.tsv"

authors:
  - "@rpetit3"
